import type { LunarLocation } from './types'

// Pre-computed 3D cartesian positions:
// x = cos(lat_rad) * cos(lon_rad)
// y = sin(lat_rad)
// z = cos(lat_rad) * sin(lon_rad)
// Camera sits on the +x axis so lon=0 (prime meridian / near-side center) faces forward.

const ARTEMIS_CREW = ['Reid Wiseman', 'Christina Koch', 'Victor Glover', 'Jeremy Hansen']

export const LOCATIONS: LunarLocation[] = [
  {
    id: 'spa',
    name: 'South Pole-Aitken Basin',
    lat: -56,
    lon: -180,
    diameter: '~2,500 km',
    significance: 'Largest, deepest, oldest known impact basin on the Moon; far side',
    isProposed: false,
    type: 'crater',
    coords: '56°S, 180°W',
    region: 'FAR SIDE',
    suggestedQuestions: [
      'What makes SPA Basin the most scientifically valuable target on the Moon?',
      "What secrets about the Moon's interior might be exposed at SPA Basin's floor?",
      'Which missions have explored this region and what did they discover?',
    ],
  },
  {
    id: 'orientale',
    name: 'Orientale Basin',
    lat: -19,
    lon: -95,
    diameter: '~900 km',
    significance: '"Bullseye" crater with 3 concentric rings; seen by human eyes for the first time by Artemis II crew',
    isProposed: false,
    type: 'crater',
    coords: '19°S, 95°W',
    region: 'FAR SIDE',
    suggestedQuestions: [
      "Why does Orientale's three-ring structure matter for understanding large impacts?",
      'What did the Artemis II crew see when they looked at Orientale for the first time?',
      'How does Orientale compare to similar multi-ring basins on other worlds?',
    ],
  },
  {
    id: 'tycho',
    name: 'Tycho',
    lat: -43,
    lon: -11,
    diameter: '85 km',
    significance: 'Most prominent young crater; bright ray system visible from Earth with naked eye',
    isProposed: false,
    type: 'crater',
    coords: '43°S, 11°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "What makes Tycho's ray system so unusually bright and long-lasting?",
      "How young is Tycho, and what can its age tell us about the Moon's recent history?",
      'What would a future mission to Tycho be looking for?',
    ],
  },
  {
    id: 'copernicus',
    name: 'Copernicus',
    lat: 10,
    lon: -20,
    diameter: '93 km',
    significance: '"Monarch of the Moon"; famous ray system and terraced walls',
    isProposed: false,
    type: 'crater',
    coords: '10°N, 20°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'Why is Copernicus called the "Monarch of the Moon"?',
      "How do Copernicus's terraced walls form and what do they reveal about the impact?",
      'Which missions have imaged Copernicus in the most detail?',
    ],
  },
  {
    id: 'clavius',
    name: 'Clavius',
    lat: -58,
    lon: -14,
    diameter: '231 km',
    significance: 'One of the largest near-side craters; famous chain of smaller craters within it',
    isProposed: false,
    type: 'crater',
    coords: '58°S, 14°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'What is the chain of craters inside Clavius and how did it form?',
      'What water ice evidence exists in the Clavius region?',
      'Why is Clavius considered one of the best candidates for a future lunar base?',
    ],
  },
  {
    id: 'bailly',
    name: 'Bailly',
    lat: -67,
    lon: -69,
    diameter: '301 km',
    significance: 'One of the largest craters on the near side; heavily degraded ancient basin',
    isProposed: false,
    type: 'crater',
    coords: '67°S, 69°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'Why is Bailly so heavily degraded compared to younger craters?',
      "What does Bailly's ancient eroded state tell us about the Moon's early bombardment history?",
      'Has any mission ever made a close-up study of Bailly?',
    ],
  },
  {
    id: 'petavius',
    name: 'Petavius',
    lat: -25,
    lon: 61,
    diameter: '184 km',
    significance: 'Prominent central peak; massive floor fracture (rille) radiating from center',
    isProposed: false,
    type: 'crater',
    coords: '25°S, 61°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "What caused the dramatic rille radiating from Petavius's central peak?",
      "How does Petavius's floor fracture compare to others on the Moon?",
      'What minerals or volcanic features are exposed at Petavius?',
    ],
  },
  {
    id: 'langrenus',
    name: 'Langrenus',
    lat: -9,
    lon: 61,
    diameter: '132 km',
    significance: 'Well-preserved; complex terraced walls and bright central peak',
    isProposed: false,
    type: 'crater',
    coords: '9°S, 61°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'What makes Langrenus one of the best-preserved complex craters on the near side?',
      'How do the bright central peaks of Langrenus form and what do they reveal about the crust?',
      'Which missions have captured the best imagery of Langrenus?',
    ],
  },
  {
    id: 'humboldt',
    name: 'Humboldt',
    lat: -27,
    lon: 81,
    diameter: '199 km',
    significance: 'Near the eastern limb; known for distinctive floor fractures',
    isProposed: false,
    type: 'crater',
    coords: '27°S, 81°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "What makes Humboldt's floor fractures scientifically interesting?",
      'Why is Humboldt difficult to observe from Earth and how has it been studied?',
      "How does Humboldt's position near the eastern limb affect exploration access?",
    ],
  },
  {
    id: 'janssen',
    name: 'Janssen',
    lat: -45,
    lon: 41,
    diameter: '201 km',
    significance: 'Ancient, heavily eroded highland crater on the southeastern near side',
    isProposed: false,
    type: 'crater',
    coords: '45°S, 41°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'How old is Janssen, and what does its heavily eroded state reveal about early lunar history?',
      'What features have survived inside Janssen despite billions of years of bombardment?',
      'Why is the southeastern near-side highland region scientifically underexplored?',
    ],
  },
  {
    id: 'schickard',
    name: 'Schickard',
    lat: -44,
    lon: -55,
    diameter: '212 km',
    significance: 'Large walled plain near the Moon\'s southwestern limb',
    isProposed: false,
    type: 'crater',
    coords: '44°S, 55°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'What is a "walled plain" and how does Schickard fit that description?',
      'What do the dark floor markings in Schickard tell us about its volcanic past?',
      'Which missions have provided the best views of Schickard?',
    ],
  },
  {
    id: 'stofler',
    name: 'Stöfler',
    lat: -41,
    lon: 6,
    diameter: '130 km',
    significance: 'Southern highlands; heavily overlapped by subsequent impacts',
    isProposed: false,
    type: 'crater',
    coords: '41°S, 6°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "How do geologists date a crater as ancient as Stöfler when its rim is so degraded?",
      "What can Stöfler's overlapping impact history tell us about the Late Heavy Bombardment?",
      'What is the highland crust made of in the Stöfler region?',
    ],
  },
  {
    id: 'maginus',
    name: 'Maginus',
    lat: -50,
    lon: -6,
    diameter: '156 km',
    significance: 'Ancient, worn crater in the rugged southern highlands',
    isProposed: false,
    type: 'crater',
    coords: '50°S, 6°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'Why is Maginus so worn compared to nearby Tycho, even though both are in the southern highlands?',
      'What geological processes have reshaped Maginus over billions of years?',
      'What can comparing Maginus and Tycho teach us?',
    ],
  },
  {
    id: 'longomontanus',
    name: 'Longomontanus',
    lat: -50,
    lon: -21,
    diameter: '146 km',
    significance: 'Large old crater southwest of Tycho',
    isProposed: false,
    type: 'crater',
    coords: '50°S, 21°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "How does Longomontanus's erosion compare to its neighbor Tycho?",
      "What has Tycho's bright ray system deposited across Longomontanus?",
      'Are there any notable features inside Longomontanus worth a closer look?',
    ],
  },
  {
    id: 'vendelinus',
    name: 'Vendelinus',
    lat: -16,
    lon: 62,
    diameter: '141 km',
    significance: 'Ancient crater on the edge of Mare Fecunditatis',
    isProposed: false,
    type: 'crater',
    coords: '16°S, 62°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'What is Mare Fecunditatis and how has its lava flooding shaped the landscape around Vendelinus?',
      'How did Vendelinus form before the nearby mare filled in around it?',
      'Which early lunar missions observed this region?',
    ],
  },
  {
    id: 'carroll',
    name: 'Carroll',
    lat: 18.84,
    lon: -86.51,
    significance: 'Sits near the near/far side boundary — visible from Earth at certain libration angles.',
    namingStory: 'Named for Carroll Taylor Wiseman, late wife of commander Reid Wiseman, who died in 2020. Described by the crew as "a bright spot on the moon."',
    isProposed: true,
    type: 'proposed',
    coords: '18.84°N, 86.51°W',
    region: 'FAR SIDE',
    namedBy: ARTEMIS_CREW,
    citations: ['NASA SVS', 'LROC', 'NASA Image Library'],
    suggestedQuestions: [
      'What do we know about the geology of this near/far-side transition zone?',
      'Which missions have photographed Carroll, and what resolution is available?',
      'Why did the Artemis II crew propose this name?',
    ],
  },
  {
    id: 'integrity',
    name: 'Integrity',
    lat: 2.66,
    lon: -104.92,
    significance: 'Located just northwest of Orientale basin on the far side of the Moon — never visible from Earth.',
    namingStory: 'Named for the Orion spacecraft on April 6, 2026, moments after the Artemis II crew broke the human distance record from Earth — the furthest any human has traveled from our planet.',
    isProposed: true,
    type: 'proposed',
    coords: '2.66°N, 104.92°W',
    region: 'FAR SIDE',
    namedBy: ARTEMIS_CREW,
    citations: ['NASA SVS', 'LROC', 'NASA Image Library'],
    suggestedQuestions: [
      'What volcanic history exists in this region?',
      'How does Integrity compare to the adjacent Orientale basin?',
      'What is the full naming story behind Integrity?',
    ],
  },
  // Apollo Landing Sites
  {
    id: 'apollo11',
    name: 'Tranquility Base',
    lat: 0.67,
    lon: 23.47,
    significance: 'First crewed lunar landing; 21.5 kg of basalt and regolith returned; Mare Tranquillitatis',
    isProposed: false,
    type: 'apollo',
    coords: '0.67°N, 23.47°E',
    region: 'NEAR SIDE',
    missionName: 'Apollo 11',
    siteName: 'Tranquility Base',
    landingYear: 1969,
    suggestedQuestions: [
      'What did the first Moon rocks from Tranquility Base reveal about the age of the lunar maria?',
      'How did the Apollo 11 landing site selection balance safety with scientific value?',
      'What traces of the Apollo 11 landing are visible in LROC imagery today?',
    ],
  },
  {
    id: 'apollo12',
    name: 'Ocean of Storms',
    lat: -3.01,
    lon: -23.42,
    significance: 'Precision landing 160m from Surveyor 3; KREEP-poor basalt; retrieved Surveyor hardware for terrestrial analysis',
    isProposed: false,
    type: 'apollo',
    coords: '3.01°S, 23.42°W',
    region: 'NEAR SIDE',
    missionName: 'Apollo 12',
    siteName: 'Ocean of Storms',
    landingYear: 1969,
    suggestedQuestions: [
      "How did Apollo 12's precision landing near Surveyor 3 change what we know about material degradation in space?",
      'What was different about the basalt composition at Apollo 12 compared to Apollo 11?',
      'Why was the ability to land within 160 meters of a target considered a guidance breakthrough?',
    ],
  },
  {
    id: 'apollo14',
    name: 'Fra Mauro',
    lat: -3.64,
    lon: -17.47,
    significance: 'Imbrium Basin ejecta blanket; KREEP-rich samples; deepest geologic window into the ancient lunar crust',
    isProposed: false,
    type: 'apollo',
    coords: '3.64°S, 17.47°W',
    region: 'NEAR SIDE',
    missionName: 'Apollo 14',
    siteName: 'Fra Mauro',
    landingYear: 1971,
    suggestedQuestions: [
      "Why is Fra Mauro considered a window into the Moon's early bombardment history?",
      "What are KREEP rocks and why were they so scientifically significant at Fra Mauro?",
      'How did the Apollo 14 samples help establish the timing of the Late Heavy Bombardment?',
    ],
  },
  {
    id: 'apollo15',
    name: 'Hadley-Apennine',
    lat: 26.13,
    lon: 3.63,
    significance: 'First lunar rover mission; Hadley Rille lava channel; the "Genesis Rock" anorthosite from primordial crust returned',
    isProposed: false,
    type: 'apollo',
    coords: '26.13°N, 3.63°E',
    region: 'NEAR SIDE',
    missionName: 'Apollo 15',
    siteName: 'Hadley-Apennine',
    landingYear: 1971,
    suggestedQuestions: [
      "What does the 'Genesis Rock' from Apollo 15 tell us about the Moon's ancient magma ocean?",
      "How did the lunar rover extend Apollo 15's reach and what did that enable scientifically?",
      'What is Hadley Rille and what does it reveal about past volcanic activity on the Moon?',
    ],
  },
  {
    id: 'apollo16',
    name: 'Descartes Highlands',
    lat: -8.97,
    lon: 15.50,
    significance: 'Only highland landing site; resolved young-volcano vs. impact origin debate; South Ray Crater samples from 100 Ma impact',
    isProposed: false,
    type: 'apollo',
    coords: '8.97°S, 15.50°E',
    region: 'NEAR SIDE',
    missionName: 'Apollo 16',
    siteName: 'Descartes',
    landingYear: 1972,
    suggestedQuestions: [
      'Why did scientists disagree about whether the Descartes highlands were volcanic, and how did Apollo 16 settle the debate?',
      'What makes the highland crust scientifically different from the mare basalts sampled at other Apollo sites?',
      'What was discovered at South Ray Crater and how old were those samples?',
    ],
  },
  {
    id: 'apollo17',
    name: 'Taurus-Littrow Valley',
    lat: 20.19,
    lon: 30.77,
    significance: 'Last crewed lunar landing; orange volcanic glass at Shorty Crater; most diverse and scientifically rich sample set returned',
    isProposed: false,
    type: 'apollo',
    coords: '20.19°N, 30.77°E',
    region: 'NEAR SIDE',
    missionName: 'Apollo 17',
    siteName: 'Taurus-Littrow',
    landingYear: 1972,
    suggestedQuestions: [
      'What does the orange soil discovered by Harrison Schmitt reveal about the volcanic history of Taurus-Littrow?',
      'Why was Taurus-Littrow chosen as the final Apollo landing site and what made it geologically unique?',
      'Which Apollo 17 samples are still being actively studied today, and why?',
    ],
  },
  // Robotic Mission Sites
  {
    id: 'surveyor3',
    name: 'Surveyor 3 Site',
    lat: -3.01,
    lon: -23.42,
    significance: 'First robotic lander later visited by humans; Apollo 12 landed 160m away and returned hardware for terrestrial analysis',
    isProposed: false,
    type: 'robotic',
    coords: '3.01°S, 23.42°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "What did returning Surveyor 3 hardware to Earth reveal about material degradation in the lunar environment?",
      "How did landing near Surveyor 3 demonstrate the precision of Apollo 12's guidance system?",
      "What does modern LROC imagery of the Surveyor 3 site show about how the hardware has changed over 50 years?",
    ],
  },
  {
    id: 'luna9',
    name: 'Luna 9 Landing Site',
    lat: 7.13,
    lon: -64.37,
    significance: 'First soft landing on any extraterrestrial body (Feb 1966); proved the lunar surface was solid and could support a lander',
    isProposed: false,
    type: 'robotic',
    coords: '7.13°N, 64.37°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "What was the scientific debate about the lunar surface before Luna 9, and how did its landing settle things?",
      "What did Luna 9's panoramic images reveal about the Oceanus Procellarum landscape?",
      "How does the Luna 9 site look in modern LROC imagery compared to what the lander photographed in 1966?",
    ],
  },
  {
    id: 'luna24',
    name: 'Luna 24 Sample Return',
    lat: 12.25,
    lon: 62.20,
    significance: 'Last Soviet lunar mission (1976); returned 170g core sample from Mare Crisium; re-analysis in 2010 found water-bearing minerals',
    isProposed: false,
    type: 'robotic',
    coords: '12.25°N, 62.20°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "How did re-analysis of Luna 24 samples in 2010 change our understanding of water in the lunar interior?",
      "What makes Mare Crisium scientifically distinct and why did the Soviets choose it for a sample return?",
      "How do Luna 24 samples compare geochemically to Apollo-era samples returned from the same decade?",
    ],
  },
  {
    id: 'change4',
    name: 'Von Kármán Crater',
    lat: -45.45,
    lon: 177.59,
    significance: 'First ever soft landing on the lunar far side (Jan 2019); Yutu-2 rover; within South Pole-Aitken Basin; requires Queqiao relay satellite',
    isProposed: false,
    type: 'robotic',
    coords: '45.45°S, 177.59°E',
    region: 'FAR SIDE',
    suggestedQuestions: [
      "Why was landing on the far side of the Moon technically so difficult, and how did China solve the relay communications problem?",
      "What has the Yutu-2 rover discovered about the mantle material exposed in Von Kármán Crater?",
      "What does the far-side geology at this location tell us that near-side missions could never reveal?",
    ],
  },
  {
    id: 'change5',
    name: 'Rümker Region',
    lat: 43.06,
    lon: -51.92,
    significance: 'Most recent lunar sample return (Dec 2020); 1.73 kg of basalt; youngest volcanic material sampled at ~2 Ga — 1 Ga younger than Apollo samples',
    isProposed: false,
    type: 'robotic',
    coords: '43.06°N, 51.92°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "Why do the Chang'e 5 samples suggest the Moon was volcanically active 2 billion years ago, much later than previously thought?",
      "How do the Rümker region basalts compare chemically to Apollo-era samples from other mare sites?",
      "What heat source could sustain lunar volcanism for so long, and what does this imply for other rocky bodies?",
    ],
  },
  {
    id: 'slim',
    name: 'SLIM Landing Site',
    lat: -13.31,
    lon: 25.25,
    significance: 'First Japanese lunar landing (Jan 2025); precision ±100m pinpoint landing near Shioli Crater; survived multiple lunar nights',
    isProposed: false,
    type: 'robotic',
    coords: '13.31°S, 25.25°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "How did JAXA's SLIM mission achieve precision landing within 100 meters of its target?",
      "What is the scientific significance of the Mare Nectaris region where SLIM landed?",
      "Why did SLIM initially land tilted, and how did it recover to complete its science objectives?",
    ],
  },
]

export function getLocationById(id: string): LunarLocation | null {
  return LOCATIONS.find((l) => l.id === id) ?? null
}
