import type { LunarLocation } from './types'

// Pre-computed 3D cartesian positions:
// x = cos(lat_rad) * cos(lon_rad)
// y = sin(lat_rad)
// z = cos(lat_rad) * sin(lon_rad)
// Camera sits on the +x axis so lon=0 (prime meridian / near-side center) faces forward.

const ARTEMIS_CREW = ['Reid Wiseman', 'Christina Koch', 'Victor Glover', 'Jeremy Hansen']

export const LOCATIONS: LunarLocation[] = [
  {
    id: 'spa',
    name: 'South Pole-Aitken Basin',
    lat: -56,
    lon: -180,
    diameter: '~2,500 km',
    significance: 'Largest, deepest, oldest known impact basin on the Moon; far side',
    isProposed: false,
    coords: '56°S, 180°W',
    region: 'FAR SIDE',
    suggestedQuestions: [
      'What makes SPA Basin the most scientifically valuable target on the Moon?',
      "What secrets about the Moon's interior might be exposed at SPA Basin's floor?",
      'Which missions have explored this region and what did they discover?',
    ],
  },
  {
    id: 'orientale',
    name: 'Orientale Basin',
    lat: -19,
    lon: -95,
    diameter: '~900 km',
    significance: '"Bullseye" crater with 3 concentric rings; seen by human eyes for the first time by Artemis II crew',
    isProposed: false,
    coords: '19°S, 95°W',
    region: 'FAR SIDE',
    suggestedQuestions: [
      "Why does Orientale's three-ring structure matter for understanding large impacts?",
      'What did the Artemis II crew see when they looked at Orientale for the first time?',
      'How does Orientale compare to similar multi-ring basins on other worlds?',
    ],
  },
  {
    id: 'tycho',
    name: 'Tycho',
    lat: -43,
    lon: -11,
    diameter: '85 km',
    significance: 'Most prominent young crater; bright ray system visible from Earth with naked eye',
    isProposed: false,
    coords: '43°S, 11°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "What makes Tycho's ray system so unusually bright and long-lasting?",
      "How young is Tycho, and what can its age tell us about the Moon's recent history?",
      'What would a future mission to Tycho be looking for?',
    ],
  },
  {
    id: 'copernicus',
    name: 'Copernicus',
    lat: 10,
    lon: -20,
    diameter: '93 km',
    significance: '"Monarch of the Moon"; famous ray system and terraced walls',
    isProposed: false,
    coords: '10°N, 20°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'Why is Copernicus called the "Monarch of the Moon"?',
      "How do Copernicus's terraced walls form and what do they reveal about the impact?",
      'Which missions have imaged Copernicus in the most detail?',
    ],
  },
  {
    id: 'clavius',
    name: 'Clavius',
    lat: -58,
    lon: -14,
    diameter: '231 km',
    significance: 'One of the largest near-side craters; famous chain of smaller craters within it',
    isProposed: false,
    coords: '58°S, 14°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'What is the chain of craters inside Clavius and how did it form?',
      'What water ice evidence exists in the Clavius region?',
      'Why is Clavius considered one of the best candidates for a future lunar base?',
    ],
  },
  {
    id: 'bailly',
    name: 'Bailly',
    lat: -67,
    lon: -69,
    diameter: '301 km',
    significance: 'One of the largest craters on the near side; heavily degraded ancient basin',
    isProposed: false,
    coords: '67°S, 69°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'Why is Bailly so heavily degraded compared to younger craters?',
      "What does Bailly's ancient eroded state tell us about the Moon's early bombardment history?",
      'Has any mission ever made a close-up study of Bailly?',
    ],
  },
  {
    id: 'petavius',
    name: 'Petavius',
    lat: -25,
    lon: 61,
    diameter: '184 km',
    significance: 'Prominent central peak; massive floor fracture (rille) radiating from center',
    isProposed: false,
    coords: '25°S, 61°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "What caused the dramatic rille radiating from Petavius's central peak?",
      "How does Petavius's floor fracture compare to others on the Moon?",
      'What minerals or volcanic features are exposed at Petavius?',
    ],
  },
  {
    id: 'langrenus',
    name: 'Langrenus',
    lat: -9,
    lon: 61,
    diameter: '132 km',
    significance: 'Well-preserved; complex terraced walls and bright central peak',
    isProposed: false,
    coords: '9°S, 61°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'What makes Langrenus one of the best-preserved complex craters on the near side?',
      'How do the bright central peaks of Langrenus form and what do they reveal about the crust?',
      'Which missions have captured the best imagery of Langrenus?',
    ],
  },
  {
    id: 'humboldt',
    name: 'Humboldt',
    lat: -27,
    lon: 81,
    diameter: '199 km',
    significance: 'Near the eastern limb; known for distinctive floor fractures',
    isProposed: false,
    coords: '27°S, 81°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "What makes Humboldt's floor fractures scientifically interesting?",
      'Why is Humboldt difficult to observe from Earth and how has it been studied?',
      "How does Humboldt's position near the eastern limb affect exploration access?",
    ],
  },
  {
    id: 'janssen',
    name: 'Janssen',
    lat: -45,
    lon: 41,
    diameter: '201 km',
    significance: 'Ancient, heavily eroded highland crater on the southeastern near side',
    isProposed: false,
    coords: '45°S, 41°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'How old is Janssen, and what does its heavily eroded state reveal about early lunar history?',
      'What features have survived inside Janssen despite billions of years of bombardment?',
      'Why is the southeastern near-side highland region scientifically underexplored?',
    ],
  },
  {
    id: 'schickard',
    name: 'Schickard',
    lat: -44,
    lon: -55,
    diameter: '212 km',
    significance: 'Large walled plain near the Moon\'s southwestern limb',
    isProposed: false,
    coords: '44°S, 55°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'What is a "walled plain" and how does Schickard fit that description?',
      'What do the dark floor markings in Schickard tell us about its volcanic past?',
      'Which missions have provided the best views of Schickard?',
    ],
  },
  {
    id: 'stofler',
    name: 'Stöfler',
    lat: -41,
    lon: 6,
    diameter: '130 km',
    significance: 'Southern highlands; heavily overlapped by subsequent impacts',
    isProposed: false,
    coords: '41°S, 6°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "How do geologists date a crater as ancient as Stöfler when its rim is so degraded?",
      "What can Stöfler's overlapping impact history tell us about the Late Heavy Bombardment?",
      'What is the highland crust made of in the Stöfler region?',
    ],
  },
  {
    id: 'maginus',
    name: 'Maginus',
    lat: -50,
    lon: -6,
    diameter: '156 km',
    significance: 'Ancient, worn crater in the rugged southern highlands',
    isProposed: false,
    coords: '50°S, 6°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'Why is Maginus so worn compared to nearby Tycho, even though both are in the southern highlands?',
      'What geological processes have reshaped Maginus over billions of years?',
      'What can comparing Maginus and Tycho teach us?',
    ],
  },
  {
    id: 'longomontanus',
    name: 'Longomontanus',
    lat: -50,
    lon: -21,
    diameter: '146 km',
    significance: 'Large old crater southwest of Tycho',
    isProposed: false,
    coords: '50°S, 21°W',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      "How does Longomontanus's erosion compare to its neighbor Tycho?",
      "What has Tycho's bright ray system deposited across Longomontanus?",
      'Are there any notable features inside Longomontanus worth a closer look?',
    ],
  },
  {
    id: 'vendelinus',
    name: 'Vendelinus',
    lat: -16,
    lon: 62,
    diameter: '141 km',
    significance: 'Ancient crater on the edge of Mare Fecunditatis',
    isProposed: false,
    coords: '16°S, 62°E',
    region: 'NEAR SIDE',
    suggestedQuestions: [
      'What is Mare Fecunditatis and how has its lava flooding shaped the landscape around Vendelinus?',
      'How did Vendelinus form before the nearby mare filled in around it?',
      'Which early lunar missions observed this region?',
    ],
  },
  {
    id: 'carroll',
    name: 'Carroll',
    lat: 18.84,
    lon: -86.51,
    significance: 'Sits near the near/far side boundary — visible from Earth at certain libration angles.',
    namingStory: 'Named for Carroll Taylor Wiseman, late wife of commander Reid Wiseman, who died in 2020. Described by the crew as "a bright spot on the moon."',
    isProposed: true,
    coords: '18.84°N, 86.51°W',
    region: 'FAR SIDE',
    namedBy: ARTEMIS_CREW,
    citations: ['NASA SVS', 'LROC', 'NASA Image Library'],
    suggestedQuestions: [
      'What do we know about the geology of this near/far-side transition zone?',
      'Which missions have photographed Carroll, and what resolution is available?',
      'Why did the Artemis II crew propose this name?',
    ],
  },
  {
    id: 'integrity',
    name: 'Integrity',
    lat: 2.66,
    lon: -104.92,
    significance: 'Located just northwest of Orientale basin on the far side of the Moon — never visible from Earth.',
    namingStory: 'Named for the Orion spacecraft on April 6, 2026, moments after the Artemis II crew broke the human distance record from Earth — the furthest any human has traveled from our planet.',
    isProposed: true,
    coords: '2.66°N, 104.92°W',
    region: 'FAR SIDE',
    namedBy: ARTEMIS_CREW,
    citations: ['NASA SVS', 'LROC', 'NASA Image Library'],
    suggestedQuestions: [
      'What volcanic history exists in this region?',
      'How does Integrity compare to the adjacent Orientale basin?',
      'What is the full naming story behind Integrity?',
    ],
  },
]

export function getLocationById(id: string): LunarLocation | null {
  return LOCATIONS.find((l) => l.id === id) ?? null
}
