import type { LunarLocation } from './types'

// Pre-computed 3D cartesian positions:
// x = cos(lat_rad) * cos(lon_rad)
// y = sin(lat_rad)
// z = cos(lat_rad) * sin(lon_rad)
// Camera sits on the +x axis so lon=0 (prime meridian / near-side center) faces forward.

const ARTEMIS_CREW = ['Reid Wiseman', 'Christina Koch', 'Victor Glover', 'Jeremy Hansen']

export const LOCATIONS: LunarLocation[] = [
  {
    id: 'spa',
    name: 'South Pole-Aitken Basin',
    lat: -56,
    lon: -180,
    diameter: '~2,500 km',
    significance: 'Largest, deepest, oldest known impact basin on the Moon; far side',
    isProposed: false,
    coords: '56°S, 180°W',
    region: 'FAR SIDE',
  },
  {
    id: 'orientale',
    name: 'Orientale Basin',
    lat: -19,
    lon: -95,
    diameter: '~900 km',
    significance: '"Bullseye" crater with 3 concentric rings; seen by human eyes for the first time by Artemis II crew',
    isProposed: false,
    coords: '19°S, 95°W',
    region: 'FAR SIDE',
  },
  {
    id: 'tycho',
    name: 'Tycho',
    lat: -43,
    lon: -11,
    diameter: '85 km',
    significance: 'Most prominent young crater; bright ray system visible from Earth with naked eye',
    isProposed: false,
    coords: '43°S, 11°W',
    region: 'NEAR SIDE',
  },
  {
    id: 'copernicus',
    name: 'Copernicus',
    lat: 10,
    lon: -20,
    diameter: '93 km',
    significance: '"Monarch of the Moon"; famous ray system and terraced walls',
    isProposed: false,
    coords: '10°N, 20°W',
    region: 'NEAR SIDE',
  },
  {
    id: 'clavius',
    name: 'Clavius',
    lat: -58,
    lon: -14,
    diameter: '231 km',
    significance: 'One of the largest near-side craters; famous chain of smaller craters within it',
    isProposed: false,
    coords: '58°S, 14°W',
    region: 'NEAR SIDE',
  },
  {
    id: 'bailly',
    name: 'Bailly',
    lat: -67,
    lon: -69,
    diameter: '301 km',
    significance: 'One of the largest craters on the near side; heavily degraded ancient basin',
    isProposed: false,
    coords: '67°S, 69°W',
    region: 'NEAR SIDE',
  },
  {
    id: 'petavius',
    name: 'Petavius',
    lat: -25,
    lon: 61,
    diameter: '184 km',
    significance: 'Prominent central peak; massive floor fracture (rille) radiating from center',
    isProposed: false,
    coords: '25°S, 61°E',
    region: 'NEAR SIDE',
  },
  {
    id: 'langrenus',
    name: 'Langrenus',
    lat: -9,
    lon: 61,
    diameter: '132 km',
    significance: 'Well-preserved; complex terraced walls and bright central peak',
    isProposed: false,
    coords: '9°S, 61°E',
    region: 'NEAR SIDE',
  },
  {
    id: 'humboldt',
    name: 'Humboldt',
    lat: -27,
    lon: 81,
    diameter: '199 km',
    significance: 'Near the eastern limb; known for distinctive floor fractures',
    isProposed: false,
    coords: '27°S, 81°E',
    region: 'NEAR SIDE',
  },
  {
    id: 'janssen',
    name: 'Janssen',
    lat: -45,
    lon: 41,
    diameter: '201 km',
    significance: 'Ancient, heavily eroded highland crater on the southeastern near side',
    isProposed: false,
    coords: '45°S, 41°E',
    region: 'NEAR SIDE',
  },
  {
    id: 'schickard',
    name: 'Schickard',
    lat: -44,
    lon: -55,
    diameter: '212 km',
    significance: 'Large walled plain near the Moon\'s southwestern limb',
    isProposed: false,
    coords: '44°S, 55°W',
    region: 'NEAR SIDE',
  },
  {
    id: 'stofler',
    name: 'Stöfler',
    lat: -41,
    lon: 6,
    diameter: '130 km',
    significance: 'Southern highlands; heavily overlapped by subsequent impacts',
    isProposed: false,
    coords: '41°S, 6°E',
    region: 'NEAR SIDE',
  },
  {
    id: 'maginus',
    name: 'Maginus',
    lat: -50,
    lon: -6,
    diameter: '156 km',
    significance: 'Ancient, worn crater in the rugged southern highlands',
    isProposed: false,
    coords: '50°S, 6°W',
    region: 'NEAR SIDE',
  },
  {
    id: 'longomontanus',
    name: 'Longomontanus',
    lat: -50,
    lon: -21,
    diameter: '146 km',
    significance: 'Large old crater southwest of Tycho',
    isProposed: false,
    coords: '50°S, 21°W',
    region: 'NEAR SIDE',
  },
  {
    id: 'vendelinus',
    name: 'Vendelinus',
    lat: -16,
    lon: 62,
    diameter: '141 km',
    significance: 'Ancient crater on the edge of Mare Fecunditatis',
    isProposed: false,
    coords: '16°S, 62°E',
    region: 'NEAR SIDE',
  },
  {
    id: 'carroll',
    name: 'Carroll',
    lat: 18.84,
    lon: -86.51,
    significance: 'Sits near the near/far side boundary — visible from Earth at certain libration angles.',
    namingStory: 'Named for Carroll Taylor Wiseman, late wife of commander Reid Wiseman, who died in 2020. Described by the crew as "a bright spot on the moon."',
    isProposed: true,
    coords: '18.84°N, 86.51°W',
    region: 'FAR SIDE',
    namedBy: ARTEMIS_CREW,
    citations: ['NASA SVS', 'LROC', 'NASA Image Library'],
    suggestedQuestions: [
      'What do we know about the geology of this near/far-side transition zone?',
      'Which missions have photographed Carroll, and what resolution is available?',
      'Why did the Artemis II crew propose this name?',
    ],
  },
  {
    id: 'integrity',
    name: 'Integrity',
    lat: 2.66,
    lon: -104.92,
    significance: 'Located just northwest of Orientale basin on the far side of the Moon — never visible from Earth.',
    namingStory: 'Named for the Orion spacecraft on April 6, 2026, moments after the Artemis II crew broke the human distance record from Earth — the furthest any human has traveled from our planet.',
    isProposed: true,
    coords: '2.66°N, 104.92°W',
    region: 'FAR SIDE',
    namedBy: ARTEMIS_CREW,
    citations: ['NASA SVS', 'LROC', 'NASA Image Library'],
    suggestedQuestions: [
      'What volcanic history exists in this region?',
      'How does Integrity compare to the adjacent Orientale basin?',
      'What is the full naming story behind Integrity?',
    ],
  },
]
